### ISSUE TITLE
Link last page

### ISSUE THREAD

**Issue by ajotah** [scratchoo/paginator#2]
Hello, I have detected that after the last update the link to go to the last page does not work, is it possible that it is like this?

**Comment by scratchoo** [comment]
Hi @ajotah I just fixed some little existing bugs, but doesn't have the time to check for the issue you described, after downloading the new updated library, can you please confirm the problem still existing ? 
have you any sample page where I can see the error (it would be very appreciated). 
**Update**
I tested in my own using the current library code and I had no issue clicking the last page link! please try it out and let me know.
Thanks

**Comment by ajotah** [comment]
Hello friend, I will explain it briefly. I use the Bulma CSS framework and when I modify the paginator.php file to add a custom configuration for Bulma the button stops working to go to the next page. However, the previous page button does work. Excuse my English. A greeting.

**Comment by scratchoo** [comment]
@ajotah I added a working Bulma configuration, the error you had is in this line : 

  `$config['next_tag_open'] = '<li><span class="pagination-ellipsis">&hellip;';
`

it should be just : 

`$config['next_tag_open'] = '<li>';`

putting the span with the class **pagination-ellipsis** inside the li tag, makes it disabled, while I don't see any need for the **...** points, but if you need them then just add another li with span before the li in the next_tag_open like this: 

`$config['next_tag_open'] = '<li><span class="pagination-ellipsis">&hellip;</span></li><li>';`

I copied the Bulma config from your fork by the way, and added the support of Bulma as part of this library, so I appreciate your contribution :)

**Comment by ajotah** [comment]
Perfect, thanks! I will modify it in my file. And I think it's great that you officially place support for Bulma CSS in this library. A greeting!
